@host = localhost:8080
@api = http://{{host}}
@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjQxMzY4NzksImlhdCI6MTcyNDEzNTk3OSwibmJmIjoxNzI0MTM1OTc5LCJzdWIiOjF9.xCd5Vr4q6X4Ih8ekreFj29BOVrDAEiQTz-SbDTcvmhb0FpEQtn9-HDJteFy1ApbDJD2ExogH5SBFsS6pQZVH7w
@userId=4
###
# Health Check
GET {{api}}/healthcheck HTTP/1.1
Content-Type: application/json

###

# Create a New User Profile
POST {{api}}/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "user_id": 1,
  "name": "Harish",
  "age": 30,
  "email":"Kapil@gmail.com",
  "image":"askduhf",
  "status":"pending"

}

###

# Get List of User Profiles
GET {{api}}/users/?page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

# Find a User Profile by ID
GET {{api}}/users/{{userId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

# Update a User Profile by ID
PUT {{api}}/users/{{userId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Updated Name",
  "email": "updated.email@example.com",
  "age": 35,
  "image":"askduhf",
  "status":"pending"
}

###

# Delete a User Profile by ID
DELETE {{api}}/users/{{userId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
