version: '3.9'

services:
  postgres:
    image: postgres:18
    container_name: postgresSanyukt
    ports:
      - "6501:5432"
    env_file:
      - ./app.env.docker
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  apigateway:
    build:
      context: ./ApiGateway
    container_name: apigateway
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      sanyuktnamdev:
        condition: service_started
    env_file:
      - ./app.env.docker
    environment:
      AUTH_SERVICE_URL: http://sanyuktnamdev:8081
      USER_SERVICE_URL: http://sanyuktnamdev:8081
      PROFILE_SERVICE_URL: http://sanyuktnamdev:8081
      BRILLIANT_STUDENT_URL: http://sanyuktnamdev:8081
      IMAGE_UPLOAD_URL: http://sanyuktnamdev:8081
      EVENTS_SERVICE_URL: http://sanyuktnamdev:8081
      BUSINESS_SERVICE_URL: http://sanyuktnamdev:8081

  sanyuktnamdev:
    build:
      context: ./SanyuktNamdev
    container_name: sanyuktnamdev
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./app.env.docker

  dbservice:
    build:
      context: ./DBService
    container_name: dbservice
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./app.env.docker

volumes:
  postgres_data: