version: '3.8'

services:
  auth-service:
    build: ./AuthService
    ports:
      - "8081:8080"
  
  user-service:
    build: ./SanyuktUserMicroservice
    ports:
      - "8082:8080"

  userprofile-service:
    build: ./SanyuktUserProfileMicroservice
    ports:
      - "8083:8083"

  upload-service:
    build: ./image-upload-service
    ports:
      - "8086:8086"
    volumes:
      - ./upload-service/uploads:/root/uploads

  namdev-events:
    build: ./namdev-events
    ports:
      - "8087:8087"

  business-service:
    build: ./business-microservice
    ports:
      - "8088:8088"
