@host = 127.0.0.1:8080
@api = http://{{host}}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDExMTA0OTUsInVzZXJpZCI6IjIifQ.CRZ51CF3MyYAfJps3inSe7qV6wgMqdQOg1r5D7duT5Q


###

POST {{api}}/register
Content-Type: application/json

{
  "name": "Harish",
  "email": "hkokcha@gmail.com", 
  "password": "qwerty"
  }
  # {"userId": "", "name": "Harish kokcha", "age": 34, "email": "harish.kokcha@gmail.com", "image": ""}
###


POST {{api}}/registerOne
Content-Type: application/json

{
  "name": "Harish",
  "email": "uiij@ds.com", 
  "password": "qwerty"
  }

###

POST {{api}}/login
Content-Type: application/json

{
  "email": "hkokcha@gmail.com",
  "password": "qwerty"
}

###

GET {{api}}/auth/protected
Authorization: Bearer {{token}}
