@host = localhost:8080
@api = http://{{host}}/auth
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzg0Nzk3ODYsInVzZXJpZCI6IjUifQ.BUIxn17ddrvmYLsHg4quzNSIkZp3AX48MCTOHMSfSbU


###

POST {{api}}/register
Content-Type: application/json

{
  "name": "Kapil",
  "email": "kapil@ds.com", 
  "password": "qwerty"
  }
  # {"userId": "", "name": "Harish kokcha", "age": 34, "email": "harish.kokcha@gmail.com", "image": ""}
###


POST {{api}}/registerOne
Content-Type: application/json

{
  "name": "Harish",
  "email": "uiij@ds.com", 
  "password": "qwerty"
  }

###

POST {{api}}/login
Content-Type: application/json

{
   "email": "kapil@ds.com", 
  "password": "qwerty"
}

###

GET {{api}}/auth/protected
Authorization: Bearer {{token}}
